Add meeting notes from Sep 9-14 2020
AcademySoftwareFoundation/OpenColorIO pull request #1142
Opened 2020-09-14 20:31 UTC by michdolan

Includes notes from last TSC meeting, ACES config, and Documentation working groups.

Signed-off-by: Michael Dolan <michdolan@gmail.com>

2020-09-16 00:30 UTC, doug-walker approved these changes
Thank you so much for taking these notes Michael, super useful!

2020-09-17 20:12 UTC, zachlewis commented
Strongly agreed; as a regular meeting-misser myself, I really appreciate the effort. It's a lot of work. I felt like a fly on the wall in that alias discussion in particular -- I like that it kind of ends on a cliffhanger.  And as a first-time meeting-attender, it's really helpful and interesting seeing my participation reflected in the minutes.

2020-09-18 13:31 UTC, hodoulp commented
Approve the TSC meeting minutes.

2020-09-18 15:20 UTC, Simran-B requested changes
Always appreciated indeed, thanks Michael!

2020-09-18 15:20 UTC, Simran-B commented on ASWF/meetings/working_groups/configs/2020-09-08.md
> +July 28, 2020
```suggestion
September 8, 2020
```

2020-09-18 15:20 UTC, Simran-B commented on ASWF/meetings/working_groups/documentation/2020-09-11.md
> +June 19, 2020
```suggestion
September 11, 2020
```

2020-09-18 15:20 UTC, Simran-B commented on ASWF/meetings/working_groups/documentation/2020-09-11.md
> +  * [X] Simran Brucherseifer
Got married 😁 
```suggestion
  * [X] Simran Spiller
```

2020-09-18 15:58 UTC, michdolan commented on ASWF/meetings/working_groups/documentation/2020-09-11.md
> +  * [X] Simran Brucherseifer
Congrats! I'll get these revisions made today.

2020-09-21 10:53 UTC, Simran-B commented on ASWF/meetings/tsc/2020-09-14.md
> +  * J Schulte - Industrial Light & Magic
Are they `[x]` or `[ ]`?

2020-09-21 11:48 UTC, michdolan commented on ASWF/meetings/tsc/2020-09-14.md
> +  * J Schulte - Industrial Light & Magic
Fixed here and for the previous week.

2020-09-22 20:18 UTC, hodoulp approved these changes
The pull request is clearly a 'small changes' one and there is already one approval so, I approve it.

2020-09-22 21:00 UTC, hodoulp commented
@michdolan The PR is ready to merge.

2020-09-23 02:23 UTC, merged