Add TSC Notes for 11-16-2020
AcademySoftwareFoundation/OpenColorIO pull request #1207
Opened 2020-11-17 01:53 UTC by carolalynn22

Signed-off-by: Carol Payne carolp@netflix.com

2020-11-17 13:29 UTC, michdolan reviewed
Thanks for the great notes @carolalynn22 ! Much appreciated.

2020-11-17 13:29 UTC, michdolan commented on ASWF/meetings/tsc/2020-11-16.md
> +    - Patrick: Yeah it's a big blob of data - the texture that you have to get onto the GPU. The structure is there to be able to generate the CUDA coda. There are two APIs - one that's openGL orenie
coda > code

2020-11-17 13:36 UTC, michdolan commented
Regarding the `NamedTransform` discussion, I'll point out this section of `PROCESS.md`:

> If one or more Committers oppose a proposed change, then the change cannot be accepted unless:
> 
> Discussions and/or additional changes result in no Committers objecting to the change. Previously-objecting Committers do not necessarily have to sign-off on the change, but they should not be opposed to it.
> 
> The change is escalated to the TSC and the TSC votes to approve the change. This should only happen if disagreements between Committers cannot be resolved through discussion.
> 
> Committers may opt to elevate significant or controversial modifications to the TSC by assigning the tsc-review label to a pull request or issue. The TSC should serve as the final arbiter where required.

I think we're still in the discussion phase of this and am hopeful we will reach an agreement there, but a reminder that if we can't this can be escalated to a TSC vote.

2020-11-17 19:00 UTC, zachlewis commented
How about an `OCIO_NIMBY` environment variable or something we could set at a facility level that would actually cause OCIO configs with named transforms to throw...? Everyone wins!

2020-11-19 00:53 UTC, doug-walker requested changes
Thank you for the notes Carol!  This was a complicated discussion and you captured it well.

2020-11-19 00:53 UTC, doug-walker commented on ASWF/meetings/tsc/2020-11-16.md
> +    - Doug: Not everyone is going to be the working space of the config.
be the working space of the config --> be solely using the working space of the config

2020-11-19 00:53 UTC, doug-walker commented on ASWF/meetings/tsc/2020-11-16.md
> +    - Doug: We can't expect everyone to have a working space per config. Even a difference between rendering space vs. compositing space. Thinking ahead to the studio config as well, it would be idea
working space per config --> have a separate config per working space

2020-11-19 00:53 UTC, doug-walker commented on ASWF/meetings/tsc/2020-11-16.md
> +    - Patrick: Yeah it's a big blob of data - the texture that you have to get onto the GPU. The structure is there to be able to generate the CUDA coda. There are two APIs - one that's openGL orenie
oreniented --> oriented

2020-11-19 00:59 UTC, doug-walker commented
> How about an `OCIO_NIMBY` environment variable or something we could set at a facility level that would actually cause OCIO configs with named transforms to throw...? Everyone wins!

Zach, thank you for trying to come up with a mutually acceptable solution.  We already added the ability to turn off Named Transforms via an env var (although it works differently than what you proposed) and ILM said it was not acceptable to them.  We are very open to your proposal but would like confirmation from ILM that it would resolve their objections before proceeding to implement it.

2020-11-20 20:52 UTC, zachlewis commented
> > How about an `OCIO_NIMBY` environment variable or something we could set at a facility level that would actually cause OCIO configs with named transforms to throw...? Everyone wins!
> 
> Zach, thank you for trying to come up with a mutually acceptable solution. We already added the ability to turn off Named Transforms via an env var (although it works differently than what you proposed) and ILM said it was not acceptable to them. We are very open to your proposal but would like confirmation from ILM that it would resolve their objections before proceeding to implement it.

Indeed. Just to be clear, what I'm proposing addresses a slightly different problem from user visibility. Matthias's "trapdoor" analogy really resonates with me; and whether named transforms are user-visible or not, just having them in a config hypothetically "poisons" the reliability of the ecosystem, in a sense (especially in light of the API's ability to construct processors "between" two configs). This doesn't sit comfortably with me.

`NamedTransforms` have the potential to cause some very insidious, difficult to diagnose problems in production, that might be too subtle for artists to notice right away; and a config that "works properly"  in some circumstances but "is broken" in others is quite a departure from what we've come to expect from OCIO-1. 

At the same time, I can't argue with user demand. Personally, the Foundry OCIO configs are the bane of my existence, and color-unmanaged shows and assets do not coexist well with color-managed shows and assets. If a supe wants to do something weird with color management, I can do my best to advise them otherwise, but at the end of the day, it's not my job to tell them "no." 

But $OCIO_NIMBY allows me to passive-aggressively say "no" per facility policy! Which is absolutely something I'd like to have the option of doing, should `NamedTransforms` come to be, visible to users or otherwise.

Also, there are certain occasions where something like `NamedTransforms` would be really useful for legitimate and semi-legitimate reasons; and a transfer function toolkit does seem kind of handy, and could potentially make configs more readable. They'd also be super useful for config-free LUT shaping, e.h. with ociobakelut. 

Maybe getting a little ahead of myself, but I thought it might be interesting if we could imbue [channel-independent] NamedTransforms with different lookup "styles", like hue_restore_dw3, max, other norms... it could be a nice way of wrapping single-channel versions of Exponent etc / Grading RGB Curves Transforms in LUT-like functionality without referencing an actual LUT.

2020-11-21 02:50 UTC, doug-walker approved these changes

2020-11-24 01:57 UTC, hodoulp approved these changes

2020-11-25 04:31 UTC, merged