RB-2.0 After Effects plug-in updates
AcademySoftwareFoundation/OpenColorIO pull request #1405
Opened 2021-05-15 20:50 UTC by fnordware

More enhancements to the the After Effects and Photoshop plug-ins, mainly making the Invert button available in all modes, not just LUTs.

Is this branch officially 2.0.1 yet?

2021-05-17 11:46 UTC, hodoulp commented
> Is this branch officially 2.0.1 yet?
No. The version 2.0.1 is out so the branch is now for 2.0.2 .

2021-06-19 01:15 UTC, doug-walker approved these changes
Thanks for adding the inversion capability!

2021-06-19 01:15 UTC, doug-walker commented on vendor/aftereffects/OpenColorIO_AE_Context.cpp
> +        _gpu_processor = _processor->getOptimizedGPUProcessor(OCIO::OPTIMIZATION_LOSSLESS);
The GPU cannot do exact inversion, so this is fine, but will be ignored.

2021-06-19 01:15 UTC, doug-walker commented on vendor/aftereffects/OpenColorIO_AE_UI.cpp
> +                assert(FALSE);
Did you intend to leave this here?

2021-06-27 21:51 UTC, michdolan commented on vendor/aftereffects/mac/OpenColorIO_AE_Dialogs_Cocoa.mm
> +            assert(config->getFamilySeparator() == '/');
This appears to be enforcing the default  `/` family separator. Can this be changed to support any separator?

2021-07-05 17:43 UTC, hodoulp commented
Hi @fnordware , what is the status of the pull request?

2021-07-06 03:42 UTC, fnordware commented
@hodoulp Looks like I'll need to find a little time to address the two comments.

2021-12-15 09:37 UTC, fnordware commented
@hodoulp By a "little time" I didn't intend for it to take me 5 months. Better late than never?

Rebased to pull in stuff that had been added to RB-2.0 in the meantime. Hopefully did the right thing.

Addressed comments by @doug-walker and @michdolan.

Should I be putting these in the RB-2.1 branch instead?

2021-12-15 14:07 UTC, hodoulp commented
Let me talk with others but I do **not** think the pull request should be merged in `RB-2.0`. That branch is only for critical bug fixes now.

2021-12-15 14:12 UTC, hodoulp requested changes
Wait to know where to merge it.

2021-12-15 19:00 UTC, fnordware commented
OK, I'll see if I get put together a RB-2.1 pull request today…

2021-12-16 01:46 UTC, fnordware commented
Never mind, we'll do it in RB-2.1.

2021-12-16 01:46 UTC, closed without merging