Fix Typo
AcademySoftwareFoundation/OpenColorIO pull request #1615
Opened 2022-03-15 17:21 UTC by sobotka

Fix minor typo in NamedTransform.

Example output currently:
```
[...]
Invoked with: kwargs: referenceSpace=<ReferenceSpaceType.REFERENCE_SPACE_DISPLAY: 1>, name='sRGB Display View', description='IEC 61966-2-1:1999 Reference sRGB Display', toReference=<NamedTransform name=Identity Transformalias=
[...]

Note how the toReference line lacks the comma.

2022-03-15 19:28 UTC, nadiashomali commented
Fix minor typo in NamedTransform.

2022-03-21 12:00 UTC, hodoulp commented
Hi @sobotka & @nadiashomali 
Thanks for your contribution.

There two points to fix:
1. The DCO failed.
2.There is a unit failure:
```
2: [ 528/1024] [MathUtils / halfs_differ_test                               ] - PASSED
2: [ 529/1024] [MathUtils / clamp                                           ] - PASSED
2: /Users/runner/work/OpenColorIO/OpenColorIO/tests/cpu/NamedTransform_tests.cpp:44:
2: FAILED: oss.str() == "<NamedTransform name=NewName,\n    forward=\n        " "<MatrixTransform direction=forward, fileindepth=unknown, " "fileoutdepth=unknown, matrix=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1, " "offset=0 0 0 0>>"
2: 	values were '<NamedTransform name=NewName, ,
2:     forward=
2:         <MatrixTransform direction=forward, fileindepth=unknown, fileoutdepth=unknown, matrix=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1, offset=0 0 0 0>>' and '<NamedTransform name=NewName,
2:     forward=
2:         <MatrixTransform direction=forward, fileindepth=unknown, fileoutdepth=unknown, matrix=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1, offset=0 0 0 0>>'
2: [ 530/1024] [NamedTransform / basic                                      ] - FAILED
2: [ 531/1024] [NamedTransform / alias                                      ] - PASSED
```

2022-03-21 12:08 UTC, hodoulp requested changes

2022-03-21 12:08 UTC, hodoulp commented on src/OpenColorIO/NamedTransform.cpp
> +    os << "name=" << strName << ", ";
If there is no aliases the line 261 prepend a comma which conflicts with the comma added here. The comma logic in the method is to always prepend a comma (and not append it). So, the comma error is in the `alias` code block.

2022-04-05 18:46 UTC, hodoulp commented
Hi @sobotka & @nadiashomali. Your finding remains a bug that it would be great to have in the next releases. After my review I found that the fix is not complete but contact us if there is still something unclear.

2024-09-23 02:23 UTC, doug-walker commented
Closing inactive PRs.

2024-09-23 02:23 UTC, closed without merging