Built-In Transform support for Apple Log
AcademySoftwareFoundation/OpenColorIO pull request #1941
Opened 2024-02-02 19:48 UTC by JGoldstone

Address request for Apple Log support as raised in #1916

2024-02-04 01:01 UTC, doug-walker requested changes
Looks great, thank you Joseph!

One more piece needs to be added. There is a check that is done in Config.cpp to ensure that a given version of the config format does not use Builtin functions that are for a newer version.  Apple Log will be the first builtin added for config format 2.4, so please add a new section [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/0c90ded16687b1b63f3e24ef417789c89b1dc509/src/OpenColorIO/Config.cpp#L5234) that tests if the new builtin is being used with older formats.

2024-02-04 03:25 UTC, JGoldstone commented on src/OpenColorIO/transforms/builtins/AppleCameras.cpp
> +        return pow(2.0, (in - delta) / gamma) - beta;
I believe these have been addressed; please review.

2024-02-04 03:27 UTC, JGoldstone commented on src/OpenColorIO/transforms/builtins/AppleCameras.cpp
> +            CreateLut(ops, 4096, APPLE_LOG::GenerateLutValues);
I have tried to mimic that code as closely as I can, but what I have produced segfaults. Is there some additional work I should be doing based on context I'm not understanding here? Your assistance would be very much appreciated.

Oh, and I added that check for config format 2.4.

2024-02-04 14:58 UTC, JGoldstone commented on src/OpenColorIO/transforms/builtins/AppleCameras.cpp
> +            CreateLut(ops, 4096, APPLE_LOG::GenerateLutValues);
Yes, it was unanticipated context. As you pointed out, this is the first builtin added that requires 2.4, but the config stored in the code as a literal to enable testing was still (reasonably enough) at 2.3. Similarly the last supported minor version for OCIO 2.x needs now to be 4, not 3. CI will tell me soon enough if I've overlooked anything else.

2024-02-04 22:58 UTC, doug-walker approved these changes
LGTM!

2024-02-05 09:25 UTC, remia approved these changes

2024-02-05 11:38 UTC, JGoldstone commented
Thanks, both of you, for the speedy review. Not having write access myself, could I ask one of you to merge the request and close this out?

2024-02-05 15:57 UTC, carolalynn22 commented
Let’s wait for Robert to take a look, please. I’ve let him know it’s up.

2024-02-05 18:13 UTC, KelSolaar commented
This would be a good PR to add as a developer guide example, i.e., how to add a new transformation.

2024-02-05 18:57 UTC, JGoldstone commented
To Thomas' point, yes, including the introspective aspects, _i.e._ not allowing the new builtins to be used in pre-3.4 configs, and being the first thing in a release to have such a constraint.

2024-02-05 21:36 UTC, zachlewis approved these changes

2024-02-06 18:41 UTC, rkmolholm commented
Looks good to me - thank you Joseph!

2024-02-07 04:37 UTC, merged

2024-02-13 06:08 UTC, doug-walker commented
@rkmolholm , after looking at the results, I'm not sure this transform is correct.  It may simply be that the footage I have was not correctly captured.  Could you point us at some known good test material in Apple Log space?