Add hasAlias method to ColorSpace and NamedTransform classes
AcademySoftwareFoundation/OpenColorIO pull request #2059
Opened 2024-09-26 21:20 UTC by annieln

Issue #2047

2024-09-26 21:52 UTC, doug-walker requested changes
This is great work Annie!  Really nice job on the unit tests!

There is one other part necessary so that the new method shows up in the Python binding too.  Please update the files:
OpenColorIO/src/bindings/python/PyColorSpace.cpp
OpenColorIO/src/bindings/python/PyNamedTransform.cpp
OpenColorIO/tests/python/ColorSpaceTest.py
OpenColorIO/tests/python/NamedTransformTest.py

The syntax using for the Python bindings (pybind11) is a bit arcane, but you should be able to copy what you see for the other methods. Let us know if you have a question.

2024-09-26 21:52 UTC, doug-walker commented on src/OpenColorIO/NamedTransform.h
> +#include "Platform.h"
Minor: Might be better moving this to the .cpp file.

2024-09-26 21:52 UTC, doug-walker commented on src/OpenColorIO/ColorSpace.cpp
> +    for (size_t idx = 0; idx < getImpl()->m_aliases.size(); ++idx) {
Very minor: The coding style for the project moves the opening bracket "{" to its own line.

2024-09-27 01:16 UTC, doug-walker approved these changes
This is excellent work, thank you so much Annie!

2024-09-27 01:19 UTC, KelSolaar approved these changes
LGTM!

2024-09-27 01:19 UTC, KelSolaar commented on tests/python/ColorSpaceTest.py
> +        Test ColorSpace aliases.
Nice catch!

2024-09-27 01:22 UTC, merged