[2057] - Fix views/display submenus in OCIODisplay app
AcademySoftwareFoundation/OpenColorIO pull request #2068
Opened 2024-09-30 18:10 UTC by hannahmkrasnick

This fixes the bug where the "Views" submenu (renamed from "Transform") doesn't update when a new "Display" is chosen (renamed submenu from "Device"). 

https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/2057#issuecomment-2383573959

2024-10-11 04:27 UTC, doug-walker requested changes
Thanks for this contribution Hannah!

Apologies for the delayed review, things have been very busy. Just one minor request below.

Minor issue, but I'm noticing a large number of white space changes. Not sure if that was you or you have an auto-formatter turned on. Although the changes are not bad, we generally don't like people to reformat white space in areas of the code they are not modifying. It makes the PR more difficult to review and it makes the git blame history of the file harder to follow. I won't ask you to waste your time reverting the changes, but please keep it in mind for future contributions.

2024-10-11 04:27 UTC, doug-walker commented on src/apps/ociodisplay/main.cpp
> +int viewsMenuID;
The other global variables have a "g_" prefix, please follow that style.

2024-11-26 05:46 UTC, doug-walker commented
@hannahmkrasnick , we would like to merge this in time for the OCIO 2.4.1 release around Dec. 9. Have you been able to make progress on getting the CLA signed?

2024-12-07 04:32 UTC, doug-walker approved these changes
This is very helpful, Hannah!  Thanks for getting the CLA signed, we will include this in OCIO 2.4.1.

2024-12-07 20:13 UTC, cozdas approved these changes

2024-12-07 20:21 UTC, merged